### PR TITLE
WIP Adding file/bytes parameter API support.

### PR DESCRIPTION
**Pull request by hazmat345**
These changes are for the API only. The UI has not been done yet.
We are only supporting gridfs for now, but these changes do allow
for file uploads as well as file streaming download.

### CODE REVIEW

**Comment by hazmat345** [comment]
I think if we're going to support file parameters the api should be v1, not vbeta.

**Comment by hazmat345** [comment]
I was able to exercise the example plugin without having to jump through too many hoops. I used the swagger API to upload the file to get the parameter dictionary.

I modified the angular-schema-form-builder so that `bytes` parameters are rendered as `dictionary` widgets, and then pasted the parameter dictionary in there, and everything Just Worked. Super cool!

**Comment by loganasherjones** [comment]
I think the file upload API should be in vbeta until we have seen it in use for some amount of time. Ideally, we won't have to change it, but I don't think we've ever dealt with relatively large parameters before and I'm not sure where the edges could be. I'd like to make sure that if we need to change the API we don't have to go through an entire release cycle.

**Comment by hazmat345** [comment]
Since this is 5 years old I don't think it's likely that this will ever be merged 😆

Closing.

**Pull request closed without merging**
